-- upgrade --
CREATE TABLE IF NOT EXISTS "message" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "text" TEXT NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    "attachment_id" CHAR(36) NOT NULL REFERENCES "attachment" ("id") ON DELETE CASCADE,
    "room_id" INT NOT NULL REFERENCES "room" ("id") ON DELETE CASCADE,
    "user_id" INT NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE
);;
CREATE TABLE IF NOT EXISTS "room" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "name" VARCHAR(30) NOT NULL
);-- downgrade --
DROP TABLE IF EXISTS "message";
DROP TABLE IF EXISTS "room";
